openapi: 3.0.2
info:
  version: 1.0.0
  title: MiNISpace
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description: >
    This is an **example** API to demonstrate features of OpenAPI specification

    # Introduction

    This API definition is intended to to be a good starting point for
    describing your API in 

    [OpenAPI/Swagger
    format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md).

    It also demonstrates features of
    [create-openapi-repo](https://github.com/Redocly/create-openapi-repo) tool
    and 

    [Redoc](https://github.com/Redocly/Redoc) documentation engine. So beyond
    the standard OpenAPI syntax we use a few 

    [vendor
    extensions](https://github.com/Redocly/Redoc/blob/master/docs/redoc-vendor-extensions.md).


    # OpenAPI Specification

    The goal of The OpenAPI Specification is to define a standard,
    language-agnostic interface to REST APIs which

    allows both humans and computers to discover and understand the capabilities
    of the service without access to source

    code, documentation, or through network traffic inspection. When properly
    defined via OpenAPI, a consumer can 

    understand and interact with the remote service with a minimal amount of
    implementation logic. Similar to what

    interfaces have done for lower-level programming, OpenAPI removes the
    guesswork in calling the service.
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Events
    description: Event operations
  - name: Auth
    description: Operations needed for authentication
  - name: Posts
    description: Post operations
  - name: OrganizingUnits
    description: Operations to manage organizing units
  - name: Users
    description: Operations to manage users
  - name: Comments
    description: Operations to work with comments
  - name: Friends
    description: Operation regarding friends relationship between users
servers:
  - url: 'http://localhost:8080/api'
paths:
  /events:
    $ref: paths/events/events.yaml
  /events/{uuid}:
    $ref: paths/events/events@{uuid}.yaml
  /events/search:
    $ref: paths/events/events@search.yaml
  /events/{eventId}/reactions:
    $ref: paths/events/events@{id}@reactions.yaml
  /events/{eventId}/participants:
    $ref: paths/events/events@{id}@participants.yaml
  /events/participatedEvents:
    $ref: paths/events/events@participatedEvents.yaml
  /users/{id}/roles:
    $ref: paths/users/users@{id}@roles.yaml
  /users/search:
    $ref: paths/users/users@search.yaml
  /posts:
    $ref: paths/posts/posts.yaml
  /posts/{postId}:
    $ref: paths/posts/posts@{postId}.yaml
  /posts/{postId}/reactions:
    $ref: paths/posts/posts@{id}@reactions.yaml
  /organizingUnits:
    $ref: paths/organizingUnits/organizingUnits.yaml
  /organizingUnits/ofUser:
    $ref: paths/organizingUnits/organizingUnits@ofUser.yaml
  /organizingUnits/{id}/user:
    $ref: paths/organizingUnits/organizingUnits@{id}@user.yaml
  /organizingUnits/roots:
    $ref: paths/organizingUnits/organizingUnits@roots.yaml
  /organizingUnits/{id}/children:
    $ref: paths/organizingUnits/organizingUnits@{id}@children.yaml
  /comments:
    $ref: paths/comments/comments.yaml
  /comments/{id}:
    $ref: paths/comments/comments@{id}.yaml
  /comments/search:
    $ref: paths/comments/comments@search.yaml
  /auth/usos/requestToken:
    $ref: paths/auth/auth@usos@requestToken.yaml
  /auth/usos/jwt:
    $ref: paths/auth/auth@usos@jwt.yaml
  /friends:
    $ref: paths/friends/friends.yaml
  /friends/search:
    $ref: paths/friends/friends@search.yaml
  /friends/{id}:
    $ref: paths/friends/friends@{id}.yaml
  /friends/requests/{id}:
    $ref: paths/friends/friends@requests@{id}.yaml
# components:
#   securitySchemes:
#     main_auth:
#       type: oauth2
#       flows:
#         implicit:
#           authorizationUrl: 'http://example.com/api/oauth/dialog'
#           scopes:
#             'read:users': read users info
#             'write:users': modify or remove users
#     api_key:
#       type: apiKey
#       in: header
#       name: api_key
#     basic_auth:
#       type: http
#       scheme: basic
